From openjdk:8
EXPOSE 8087
copy ./target/springboot-microservice-app-0.0.1-SNAPSHOT.jar springboot-microservice-app-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","springboot-microservice-app-0.0.1-SNAPSHOT.jar"]